RUN install.packages("remotes")
RUN library(remotes)
RUN remotes::install_version("purrr", version = "0.3.4")
RUN library(purrr)
RUN remotes::install_version("dplyr", version = "1.0.10")
RUN library(dplyr)
RUN remotes::install_version("tidyr", version = "1.1.2")
RUN library(tidyr)
RUN remotes::install_version("tibble", version = "3.1.8")
RUN library(tibble)
RUN remotes::install_version("tidyselect", version = "1.1.0")
RUN library(tidyselect)
RUN remotes::install_version("vctrs", version = "0.3.8")
RUN library(vctrs)
RUN install.packages("rlang", repos = "https://cloud.r-project.org/")
RUN library(rlang)
RUN remotes::install_version("tidytext", version = "0.3.3")
RUN library(tidytext)
RUN install.packages("ggplot2")
RUN library(ggplot2)